/**
 * Auto-generated by db:generate-from-metadata. Do not edit manually.
 */
import { organizations, users, tenants } from '../db/schema.js'

export const tenantConfig = { mode: 'org_and_tenant' } as const

export const entityRegistry = {
  'organizations': { table: organizations, objectName: 'organization', searchFields: [organizations.name, organizations.slug, organizations.logo, organizations.address, organizations.defaultCurrency, organizations.currencySymbol, organizations.timezone, organizations.defaultPreferredLanguage, organizations.sidebarTheme, organizations.maxStorageBytes], insertFields: ['name', 'slug', 'logo', 'address', 'defaultCurrency', 'currencySymbol', 'timezone', 'defaultPreferredLanguage', 'sidebarTheme', 'maxStorageBytes', 'createdAt', 'updatedAt', 'createdById', 'ownerId'], updateFields: ['name', 'slug', 'logo', 'address', 'defaultCurrency', 'currencySymbol', 'timezone', 'defaultPreferredLanguage', 'sidebarTheme', 'maxStorageBytes', 'updatedAt', 'ownerId', 'editedById'], referenceFields: [{ key: 'createdBy', idField: 'createdById', refTable: 'users' }, { key: 'owner', idField: 'ownerId', refTable: 'users' }, { key: 'editedBy', idField: 'editedById', refTable: 'users' }], computedFields: undefined, relatedListPaths: undefined },
  'tenants': { table: tenants, objectName: 'tenant', searchFields: [tenants.name, tenants.logo, tenants.address, tenants.defaultCurrency, tenants.currencySymbol, tenants.timezone, tenants.defaultPreferredLanguage, tenants.sidebarTheme, tenants.maxStorageBytes], insertFields: ['name', 'logo', 'address', 'defaultCurrency', 'currencySymbol', 'timezone', 'defaultPreferredLanguage', 'sidebarTheme', 'maxStorageBytes', 'organizationId', 'createdAt', 'updatedAt', 'createdById', 'ownerId'], updateFields: ['name', 'logo', 'address', 'defaultCurrency', 'currencySymbol', 'timezone', 'defaultPreferredLanguage', 'sidebarTheme', 'maxStorageBytes', 'organizationId', 'updatedAt', 'ownerId', 'editedById'], referenceFields: [{ key: 'organization', idField: 'organizationId', refTable: 'organizations' }, { key: 'createdBy', idField: 'createdById', refTable: 'users' }, { key: 'owner', idField: 'ownerId', refTable: 'users' }, { key: 'editedBy', idField: 'editedById', refTable: 'users' }], requiredRefIdFields: ['organizationId'], join: { joinTable: organizations, leftColumn: tenants.organizationId, rightColumn: organizations.id }, computedFields: undefined, relatedListPaths: {"organization":{"filterColumn":"organizationId"}} },
} as const

export type EntityPath = keyof typeof entityRegistry
