/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SecureAccessRouteImport } from './routes/secure-access'
import { Route as LoginVerify2faRouteImport } from './routes/login-verify-2fa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfirmEmailChangeRouteImport } from './routes/confirm-email-change'
import { Route as ChangePasswordRequiredRouteImport } from './routes/change-password-required'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedFilesRouteImport } from './routes/_authenticated/files'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedObjectNameIndexRouteImport } from './routes/_authenticated/$objectName/index'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsTranslationsRouteImport } from './routes/_authenticated/settings/translations'
import { Route as AuthenticatedSettingsTenantRouteImport } from './routes/_authenticated/settings/tenant'
import { Route as AuthenticatedSettingsSidebarAssignmentRouteImport } from './routes/_authenticated/settings/sidebar-assignment'
import { Route as AuthenticatedSettingsProfilesRouteImport } from './routes/_authenticated/settings/profiles'
import { Route as AuthenticatedSettingsOrganizationRouteImport } from './routes/_authenticated/settings/organization'
import { Route as AuthenticatedSettingsObjectManagerRouteImport } from './routes/_authenticated/settings/object-manager'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsNotificationSettingsRouteImport } from './routes/_authenticated/settings/notification-settings'
import { Route as AuthenticatedSettingsFilesRouteImport } from './routes/_authenticated/settings/files'
import { Route as AuthenticatedSettingsEmailTemplatesRouteImport } from './routes/_authenticated/settings/email-templates'
import { Route as AuthenticatedSettingsEmailRouteImport } from './routes/_authenticated/settings/email'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedDevComponentsSalesforcePathRouteImport } from './routes/_authenticated/dev-components/salesforce-path'
import { Route as AuthenticatedDevComponentsOrderDetailPathRouteImport } from './routes/_authenticated/dev-components/order-detail-path'
import { Route as AuthenticatedDevComponentsDetailViewFormatterRouteImport } from './routes/_authenticated/dev-components/detail-view-formatter'
import { Route as AuthenticatedObjectNameRecordIdRouteImport } from './routes/_authenticated/$objectName/$recordId'
import { Route as AuthenticatedSettingsUsersIndexRouteImport } from './routes/_authenticated/settings/users/index'
import { Route as AuthenticatedSettingsTranslationsIndexRouteImport } from './routes/_authenticated/settings/translations/index'
import { Route as AuthenticatedSettingsSidebarAssignmentIndexRouteImport } from './routes/_authenticated/settings/sidebar-assignment/index'
import { Route as AuthenticatedSettingsProfilesIndexRouteImport } from './routes/_authenticated/settings/profiles/index'
import { Route as AuthenticatedSettingsObjectManagerIndexRouteImport } from './routes/_authenticated/settings/object-manager/index'
import { Route as AuthenticatedSettingsEmailTemplatesIndexRouteImport } from './routes/_authenticated/settings/email-templates/index'
import { Route as AuthenticatedSettingsUsersUserIdRouteImport } from './routes/_authenticated/settings/users/$userId'
import { Route as AuthenticatedSettingsProfilesProfileNameRouteImport } from './routes/_authenticated/settings/profiles/$profileName'
import { Route as AuthenticatedSettingsObjectManagerObjectNameRouteImport } from './routes/_authenticated/settings/object-manager/$objectName'
import { Route as AuthenticatedSettingsEmailTemplatesTemplateKeyRouteImport } from './routes/_authenticated/settings/email-templates/$templateKey'
import { Route as AuthenticatedSettingsProfilesProfileNameIndexRouteImport } from './routes/_authenticated/settings/profiles/$profileName/index'
import { Route as AuthenticatedSettingsProfilesProfileNameObjectsRouteImport } from './routes/_authenticated/settings/profiles/$profileName/objects'
import { Route as AuthenticatedSettingsProfilesProfileNameListViewsRouteImport } from './routes/_authenticated/settings/profiles/$profileName/list-views'
import { Route as AuthenticatedSettingsProfilesProfileNameGlobalActionsRouteImport } from './routes/_authenticated/settings/profiles/$profileName/global-actions'
import { Route as AuthenticatedSettingsProfilesProfileNameObjectsIndexRouteImport } from './routes/_authenticated/settings/profiles/$profileName/objects/index'
import { Route as AuthenticatedSettingsProfilesProfileNameObjectsObjectNameRouteImport } from './routes/_authenticated/settings/profiles/$profileName/objects/$objectName'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SecureAccessRoute = SecureAccessRouteImport.update({
  id: '/secure-access',
  path: '/secure-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginVerify2faRoute = LoginVerify2faRouteImport.update({
  id: '/login-verify-2fa',
  path: '/login-verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailChangeRoute = ConfirmEmailChangeRouteImport.update({
  id: '/confirm-email-change',
  path: '/confirm-email-change',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRequiredRoute = ChangePasswordRequiredRouteImport.update({
  id: '/change-password-required',
  path: '/change-password-required',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilesRoute = AuthenticatedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObjectNameIndexRoute =
  AuthenticatedObjectNameIndexRouteImport.update({
    id: '/$objectName/',
    path: '/$objectName/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsTranslationsRoute =
  AuthenticatedSettingsTranslationsRouteImport.update({
    id: '/translations',
    path: '/translations',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsTenantRoute =
  AuthenticatedSettingsTenantRouteImport.update({
    id: '/tenant',
    path: '/tenant',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsSidebarAssignmentRoute =
  AuthenticatedSettingsSidebarAssignmentRouteImport.update({
    id: '/sidebar-assignment',
    path: '/sidebar-assignment',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsProfilesRoute =
  AuthenticatedSettingsProfilesRouteImport.update({
    id: '/profiles',
    path: '/profiles',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsOrganizationRoute =
  AuthenticatedSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsObjectManagerRoute =
  AuthenticatedSettingsObjectManagerRouteImport.update({
    id: '/object-manager',
    path: '/object-manager',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationSettingsRoute =
  AuthenticatedSettingsNotificationSettingsRouteImport.update({
    id: '/notification-settings',
    path: '/notification-settings',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsFilesRoute =
  AuthenticatedSettingsFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsEmailTemplatesRoute =
  AuthenticatedSettingsEmailTemplatesRouteImport.update({
    id: '/email-templates',
    path: '/email-templates',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsEmailRoute =
  AuthenticatedSettingsEmailRouteImport.update({
    id: '/email',
    path: '/email',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedDevComponentsSalesforcePathRoute =
  AuthenticatedDevComponentsSalesforcePathRouteImport.update({
    id: '/dev-components/salesforce-path',
    path: '/dev-components/salesforce-path',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevComponentsOrderDetailPathRoute =
  AuthenticatedDevComponentsOrderDetailPathRouteImport.update({
    id: '/dev-components/order-detail-path',
    path: '/dev-components/order-detail-path',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevComponentsDetailViewFormatterRoute =
  AuthenticatedDevComponentsDetailViewFormatterRouteImport.update({
    id: '/dev-components/detail-view-formatter',
    path: '/dev-components/detail-view-formatter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObjectNameRecordIdRoute =
  AuthenticatedObjectNameRecordIdRouteImport.update({
    id: '/$objectName/$recordId',
    path: '/$objectName/$recordId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsUsersIndexRoute =
  AuthenticatedSettingsUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsUsersRoute,
  } as any)
const AuthenticatedSettingsTranslationsIndexRoute =
  AuthenticatedSettingsTranslationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsTranslationsRoute,
  } as any)
const AuthenticatedSettingsSidebarAssignmentIndexRoute =
  AuthenticatedSettingsSidebarAssignmentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsSidebarAssignmentRoute,
  } as any)
const AuthenticatedSettingsProfilesIndexRoute =
  AuthenticatedSettingsProfilesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsProfilesRoute,
  } as any)
const AuthenticatedSettingsObjectManagerIndexRoute =
  AuthenticatedSettingsObjectManagerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsObjectManagerRoute,
  } as any)
const AuthenticatedSettingsEmailTemplatesIndexRoute =
  AuthenticatedSettingsEmailTemplatesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsEmailTemplatesRoute,
  } as any)
const AuthenticatedSettingsUsersUserIdRoute =
  AuthenticatedSettingsUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedSettingsUsersRoute,
  } as any)
const AuthenticatedSettingsProfilesProfileNameRoute =
  AuthenticatedSettingsProfilesProfileNameRouteImport.update({
    id: '/$profileName',
    path: '/$profileName',
    getParentRoute: () => AuthenticatedSettingsProfilesRoute,
  } as any)
const AuthenticatedSettingsObjectManagerObjectNameRoute =
  AuthenticatedSettingsObjectManagerObjectNameRouteImport.update({
    id: '/$objectName',
    path: '/$objectName',
    getParentRoute: () => AuthenticatedSettingsObjectManagerRoute,
  } as any)
const AuthenticatedSettingsEmailTemplatesTemplateKeyRoute =
  AuthenticatedSettingsEmailTemplatesTemplateKeyRouteImport.update({
    id: '/$templateKey',
    path: '/$templateKey',
    getParentRoute: () => AuthenticatedSettingsEmailTemplatesRoute,
  } as any)
const AuthenticatedSettingsProfilesProfileNameIndexRoute =
  AuthenticatedSettingsProfilesProfileNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsProfilesProfileNameRoute,
  } as any)
const AuthenticatedSettingsProfilesProfileNameObjectsRoute =
  AuthenticatedSettingsProfilesProfileNameObjectsRouteImport.update({
    id: '/objects',
    path: '/objects',
    getParentRoute: () => AuthenticatedSettingsProfilesProfileNameRoute,
  } as any)
const AuthenticatedSettingsProfilesProfileNameListViewsRoute =
  AuthenticatedSettingsProfilesProfileNameListViewsRouteImport.update({
    id: '/list-views',
    path: '/list-views',
    getParentRoute: () => AuthenticatedSettingsProfilesProfileNameRoute,
  } as any)
const AuthenticatedSettingsProfilesProfileNameGlobalActionsRoute =
  AuthenticatedSettingsProfilesProfileNameGlobalActionsRouteImport.update({
    id: '/global-actions',
    path: '/global-actions',
    getParentRoute: () => AuthenticatedSettingsProfilesProfileNameRoute,
  } as any)
const AuthenticatedSettingsProfilesProfileNameObjectsIndexRoute =
  AuthenticatedSettingsProfilesProfileNameObjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsProfilesProfileNameObjectsRoute,
  } as any)
const AuthenticatedSettingsProfilesProfileNameObjectsObjectNameRoute =
  AuthenticatedSettingsProfilesProfileNameObjectsObjectNameRouteImport.update({
    id: '/$objectName',
    path: '/$objectName',
    getParentRoute: () => AuthenticatedSettingsProfilesProfileNameObjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password-required': typeof ChangePasswordRequiredRoute
  '/confirm-email-change': typeof ConfirmEmailChangeRoute
  '/login': typeof LoginRoute
  '/login-verify-2fa': typeof LoginVerify2faRoute
  '/secure-access': typeof SecureAccessRoute
  '/verify-email': typeof VerifyEmailRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/files': typeof AuthenticatedFilesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/$objectName/$recordId': typeof AuthenticatedObjectNameRecordIdRoute
  '/dev-components/detail-view-formatter': typeof AuthenticatedDevComponentsDetailViewFormatterRoute
  '/dev-components/order-detail-path': typeof AuthenticatedDevComponentsOrderDetailPathRoute
  '/dev-components/salesforce-path': typeof AuthenticatedDevComponentsSalesforcePathRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/settings/email-templates': typeof AuthenticatedSettingsEmailTemplatesRouteWithChildren
  '/settings/files': typeof AuthenticatedSettingsFilesRoute
  '/settings/notification-settings': typeof AuthenticatedSettingsNotificationSettingsRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/object-manager': typeof AuthenticatedSettingsObjectManagerRouteWithChildren
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/profiles': typeof AuthenticatedSettingsProfilesRouteWithChildren
  '/settings/sidebar-assignment': typeof AuthenticatedSettingsSidebarAssignmentRouteWithChildren
  '/settings/tenant': typeof AuthenticatedSettingsTenantRoute
  '/settings/translations': typeof AuthenticatedSettingsTranslationsRouteWithChildren
  '/settings/users': typeof AuthenticatedSettingsUsersRouteWithChildren
  '/$objectName': typeof AuthenticatedObjectNameIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/settings/email-templates/$templateKey': typeof AuthenticatedSettingsEmailTemplatesTemplateKeyRoute
  '/settings/object-manager/$objectName': typeof AuthenticatedSettingsObjectManagerObjectNameRoute
  '/settings/profiles/$profileName': typeof AuthenticatedSettingsProfilesProfileNameRouteWithChildren
  '/settings/users/$userId': typeof AuthenticatedSettingsUsersUserIdRoute
  '/settings/email-templates/': typeof AuthenticatedSettingsEmailTemplatesIndexRoute
  '/settings/object-manager/': typeof AuthenticatedSettingsObjectManagerIndexRoute
  '/settings/profiles/': typeof AuthenticatedSettingsProfilesIndexRoute
  '/settings/sidebar-assignment/': typeof AuthenticatedSettingsSidebarAssignmentIndexRoute
  '/settings/translations/': typeof AuthenticatedSettingsTranslationsIndexRoute
  '/settings/users/': typeof AuthenticatedSettingsUsersIndexRoute
  '/settings/profiles/$profileName/global-actions': typeof AuthenticatedSettingsProfilesProfileNameGlobalActionsRoute
  '/settings/profiles/$profileName/list-views': typeof AuthenticatedSettingsProfilesProfileNameListViewsRoute
  '/settings/profiles/$profileName/objects': typeof AuthenticatedSettingsProfilesProfileNameObjectsRouteWithChildren
  '/settings/profiles/$profileName/': typeof AuthenticatedSettingsProfilesProfileNameIndexRoute
  '/settings/profiles/$profileName/objects/$objectName': typeof AuthenticatedSettingsProfilesProfileNameObjectsObjectNameRoute
  '/settings/profiles/$profileName/objects/': typeof AuthenticatedSettingsProfilesProfileNameObjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password-required': typeof ChangePasswordRequiredRoute
  '/confirm-email-change': typeof ConfirmEmailChangeRoute
  '/login': typeof LoginRoute
  '/login-verify-2fa': typeof LoginVerify2faRoute
  '/secure-access': typeof SecureAccessRoute
  '/verify-email': typeof VerifyEmailRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/files': typeof AuthenticatedFilesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/$objectName/$recordId': typeof AuthenticatedObjectNameRecordIdRoute
  '/dev-components/detail-view-formatter': typeof AuthenticatedDevComponentsDetailViewFormatterRoute
  '/dev-components/order-detail-path': typeof AuthenticatedDevComponentsOrderDetailPathRoute
  '/dev-components/salesforce-path': typeof AuthenticatedDevComponentsSalesforcePathRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/settings/files': typeof AuthenticatedSettingsFilesRoute
  '/settings/notification-settings': typeof AuthenticatedSettingsNotificationSettingsRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/settings/tenant': typeof AuthenticatedSettingsTenantRoute
  '/$objectName': typeof AuthenticatedObjectNameIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/settings/email-templates/$templateKey': typeof AuthenticatedSettingsEmailTemplatesTemplateKeyRoute
  '/settings/object-manager/$objectName': typeof AuthenticatedSettingsObjectManagerObjectNameRoute
  '/settings/users/$userId': typeof AuthenticatedSettingsUsersUserIdRoute
  '/settings/email-templates': typeof AuthenticatedSettingsEmailTemplatesIndexRoute
  '/settings/object-manager': typeof AuthenticatedSettingsObjectManagerIndexRoute
  '/settings/profiles': typeof AuthenticatedSettingsProfilesIndexRoute
  '/settings/sidebar-assignment': typeof AuthenticatedSettingsSidebarAssignmentIndexRoute
  '/settings/translations': typeof AuthenticatedSettingsTranslationsIndexRoute
  '/settings/users': typeof AuthenticatedSettingsUsersIndexRoute
  '/settings/profiles/$profileName/global-actions': typeof AuthenticatedSettingsProfilesProfileNameGlobalActionsRoute
  '/settings/profiles/$profileName/list-views': typeof AuthenticatedSettingsProfilesProfileNameListViewsRoute
  '/settings/profiles/$profileName': typeof AuthenticatedSettingsProfilesProfileNameIndexRoute
  '/settings/profiles/$profileName/objects/$objectName': typeof AuthenticatedSettingsProfilesProfileNameObjectsObjectNameRoute
  '/settings/profiles/$profileName/objects': typeof AuthenticatedSettingsProfilesProfileNameObjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/change-password-required': typeof ChangePasswordRequiredRoute
  '/confirm-email-change': typeof ConfirmEmailChangeRoute
  '/login': typeof LoginRoute
  '/login-verify-2fa': typeof LoginVerify2faRoute
  '/secure-access': typeof SecureAccessRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/files': typeof AuthenticatedFilesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/$objectName/$recordId': typeof AuthenticatedObjectNameRecordIdRoute
  '/_authenticated/dev-components/detail-view-formatter': typeof AuthenticatedDevComponentsDetailViewFormatterRoute
  '/_authenticated/dev-components/order-detail-path': typeof AuthenticatedDevComponentsOrderDetailPathRoute
  '/_authenticated/dev-components/salesforce-path': typeof AuthenticatedDevComponentsSalesforcePathRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/_authenticated/settings/email-templates': typeof AuthenticatedSettingsEmailTemplatesRouteWithChildren
  '/_authenticated/settings/files': typeof AuthenticatedSettingsFilesRoute
  '/_authenticated/settings/notification-settings': typeof AuthenticatedSettingsNotificationSettingsRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/object-manager': typeof AuthenticatedSettingsObjectManagerRouteWithChildren
  '/_authenticated/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/_authenticated/settings/profiles': typeof AuthenticatedSettingsProfilesRouteWithChildren
  '/_authenticated/settings/sidebar-assignment': typeof AuthenticatedSettingsSidebarAssignmentRouteWithChildren
  '/_authenticated/settings/tenant': typeof AuthenticatedSettingsTenantRoute
  '/_authenticated/settings/translations': typeof AuthenticatedSettingsTranslationsRouteWithChildren
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRouteWithChildren
  '/_authenticated/$objectName/': typeof AuthenticatedObjectNameIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/settings/email-templates/$templateKey': typeof AuthenticatedSettingsEmailTemplatesTemplateKeyRoute
  '/_authenticated/settings/object-manager/$objectName': typeof AuthenticatedSettingsObjectManagerObjectNameRoute
  '/_authenticated/settings/profiles/$profileName': typeof AuthenticatedSettingsProfilesProfileNameRouteWithChildren
  '/_authenticated/settings/users/$userId': typeof AuthenticatedSettingsUsersUserIdRoute
  '/_authenticated/settings/email-templates/': typeof AuthenticatedSettingsEmailTemplatesIndexRoute
  '/_authenticated/settings/object-manager/': typeof AuthenticatedSettingsObjectManagerIndexRoute
  '/_authenticated/settings/profiles/': typeof AuthenticatedSettingsProfilesIndexRoute
  '/_authenticated/settings/sidebar-assignment/': typeof AuthenticatedSettingsSidebarAssignmentIndexRoute
  '/_authenticated/settings/translations/': typeof AuthenticatedSettingsTranslationsIndexRoute
  '/_authenticated/settings/users/': typeof AuthenticatedSettingsUsersIndexRoute
  '/_authenticated/settings/profiles/$profileName/global-actions': typeof AuthenticatedSettingsProfilesProfileNameGlobalActionsRoute
  '/_authenticated/settings/profiles/$profileName/list-views': typeof AuthenticatedSettingsProfilesProfileNameListViewsRoute
  '/_authenticated/settings/profiles/$profileName/objects': typeof AuthenticatedSettingsProfilesProfileNameObjectsRouteWithChildren
  '/_authenticated/settings/profiles/$profileName/': typeof AuthenticatedSettingsProfilesProfileNameIndexRoute
  '/_authenticated/settings/profiles/$profileName/objects/$objectName': typeof AuthenticatedSettingsProfilesProfileNameObjectsObjectNameRoute
  '/_authenticated/settings/profiles/$profileName/objects/': typeof AuthenticatedSettingsProfilesProfileNameObjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password-required'
    | '/confirm-email-change'
    | '/login'
    | '/login-verify-2fa'
    | '/secure-access'
    | '/verify-email'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/billing'
    | '/dashboard'
    | '/files'
    | '/profile'
    | '/$objectName/$recordId'
    | '/dev-components/detail-view-formatter'
    | '/dev-components/order-detail-path'
    | '/dev-components/salesforce-path'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/email'
    | '/settings/email-templates'
    | '/settings/files'
    | '/settings/notification-settings'
    | '/settings/notifications'
    | '/settings/object-manager'
    | '/settings/organization'
    | '/settings/profiles'
    | '/settings/sidebar-assignment'
    | '/settings/tenant'
    | '/settings/translations'
    | '/settings/users'
    | '/$objectName'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/settings/email-templates/$templateKey'
    | '/settings/object-manager/$objectName'
    | '/settings/profiles/$profileName'
    | '/settings/users/$userId'
    | '/settings/email-templates/'
    | '/settings/object-manager/'
    | '/settings/profiles/'
    | '/settings/sidebar-assignment/'
    | '/settings/translations/'
    | '/settings/users/'
    | '/settings/profiles/$profileName/global-actions'
    | '/settings/profiles/$profileName/list-views'
    | '/settings/profiles/$profileName/objects'
    | '/settings/profiles/$profileName/'
    | '/settings/profiles/$profileName/objects/$objectName'
    | '/settings/profiles/$profileName/objects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password-required'
    | '/confirm-email-change'
    | '/login'
    | '/login-verify-2fa'
    | '/secure-access'
    | '/verify-email'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/billing'
    | '/dashboard'
    | '/files'
    | '/profile'
    | '/$objectName/$recordId'
    | '/dev-components/detail-view-formatter'
    | '/dev-components/order-detail-path'
    | '/dev-components/salesforce-path'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/email'
    | '/settings/files'
    | '/settings/notification-settings'
    | '/settings/notifications'
    | '/settings/organization'
    | '/settings/tenant'
    | '/$objectName'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/settings/email-templates/$templateKey'
    | '/settings/object-manager/$objectName'
    | '/settings/users/$userId'
    | '/settings/email-templates'
    | '/settings/object-manager'
    | '/settings/profiles'
    | '/settings/sidebar-assignment'
    | '/settings/translations'
    | '/settings/users'
    | '/settings/profiles/$profileName/global-actions'
    | '/settings/profiles/$profileName/list-views'
    | '/settings/profiles/$profileName'
    | '/settings/profiles/$profileName/objects/$objectName'
    | '/settings/profiles/$profileName/objects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/change-password-required'
    | '/confirm-email-change'
    | '/login'
    | '/login-verify-2fa'
    | '/secure-access'
    | '/verify-email'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/files'
    | '/_authenticated/profile'
    | '/_authenticated/$objectName/$recordId'
    | '/_authenticated/dev-components/detail-view-formatter'
    | '/_authenticated/dev-components/order-detail-path'
    | '/_authenticated/dev-components/salesforce-path'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/email'
    | '/_authenticated/settings/email-templates'
    | '/_authenticated/settings/files'
    | '/_authenticated/settings/notification-settings'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/object-manager'
    | '/_authenticated/settings/organization'
    | '/_authenticated/settings/profiles'
    | '/_authenticated/settings/sidebar-assignment'
    | '/_authenticated/settings/tenant'
    | '/_authenticated/settings/translations'
    | '/_authenticated/settings/users'
    | '/_authenticated/$objectName/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/settings/email-templates/$templateKey'
    | '/_authenticated/settings/object-manager/$objectName'
    | '/_authenticated/settings/profiles/$profileName'
    | '/_authenticated/settings/users/$userId'
    | '/_authenticated/settings/email-templates/'
    | '/_authenticated/settings/object-manager/'
    | '/_authenticated/settings/profiles/'
    | '/_authenticated/settings/sidebar-assignment/'
    | '/_authenticated/settings/translations/'
    | '/_authenticated/settings/users/'
    | '/_authenticated/settings/profiles/$profileName/global-actions'
    | '/_authenticated/settings/profiles/$profileName/list-views'
    | '/_authenticated/settings/profiles/$profileName/objects'
    | '/_authenticated/settings/profiles/$profileName/'
    | '/_authenticated/settings/profiles/$profileName/objects/$objectName'
    | '/_authenticated/settings/profiles/$profileName/objects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ChangePasswordRequiredRoute: typeof ChangePasswordRequiredRoute
  ConfirmEmailChangeRoute: typeof ConfirmEmailChangeRoute
  LoginRoute: typeof LoginRoute
  LoginVerify2faRoute: typeof LoginVerify2faRoute
  SecureAccessRoute: typeof SecureAccessRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secure-access': {
      id: '/secure-access'
      path: '/secure-access'
      fullPath: '/secure-access'
      preLoaderRoute: typeof SecureAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-verify-2fa': {
      id: '/login-verify-2fa'
      path: '/login-verify-2fa'
      fullPath: '/login-verify-2fa'
      preLoaderRoute: typeof LoginVerify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email-change': {
      id: '/confirm-email-change'
      path: '/confirm-email-change'
      fullPath: '/confirm-email-change'
      preLoaderRoute: typeof ConfirmEmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password-required': {
      id: '/change-password-required'
      path: '/change-password-required'
      fullPath: '/change-password-required'
      preLoaderRoute: typeof ChangePasswordRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/files': {
      id: '/_authenticated/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$objectName/': {
      id: '/_authenticated/$objectName/'
      path: '/$objectName'
      fullPath: '/$objectName'
      preLoaderRoute: typeof AuthenticatedObjectNameIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/translations': {
      id: '/_authenticated/settings/translations'
      path: '/translations'
      fullPath: '/settings/translations'
      preLoaderRoute: typeof AuthenticatedSettingsTranslationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/tenant': {
      id: '/_authenticated/settings/tenant'
      path: '/tenant'
      fullPath: '/settings/tenant'
      preLoaderRoute: typeof AuthenticatedSettingsTenantRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/sidebar-assignment': {
      id: '/_authenticated/settings/sidebar-assignment'
      path: '/sidebar-assignment'
      fullPath: '/settings/sidebar-assignment'
      preLoaderRoute: typeof AuthenticatedSettingsSidebarAssignmentRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/profiles': {
      id: '/_authenticated/settings/profiles'
      path: '/profiles'
      fullPath: '/settings/profiles'
      preLoaderRoute: typeof AuthenticatedSettingsProfilesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/organization': {
      id: '/_authenticated/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/object-manager': {
      id: '/_authenticated/settings/object-manager'
      path: '/object-manager'
      fullPath: '/settings/object-manager'
      preLoaderRoute: typeof AuthenticatedSettingsObjectManagerRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notification-settings': {
      id: '/_authenticated/settings/notification-settings'
      path: '/notification-settings'
      fullPath: '/settings/notification-settings'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationSettingsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/files': {
      id: '/_authenticated/settings/files'
      path: '/files'
      fullPath: '/settings/files'
      preLoaderRoute: typeof AuthenticatedSettingsFilesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/email-templates': {
      id: '/_authenticated/settings/email-templates'
      path: '/email-templates'
      fullPath: '/settings/email-templates'
      preLoaderRoute: typeof AuthenticatedSettingsEmailTemplatesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/email': {
      id: '/_authenticated/settings/email'
      path: '/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof AuthenticatedSettingsEmailRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/dev-components/salesforce-path': {
      id: '/_authenticated/dev-components/salesforce-path'
      path: '/dev-components/salesforce-path'
      fullPath: '/dev-components/salesforce-path'
      preLoaderRoute: typeof AuthenticatedDevComponentsSalesforcePathRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev-components/order-detail-path': {
      id: '/_authenticated/dev-components/order-detail-path'
      path: '/dev-components/order-detail-path'
      fullPath: '/dev-components/order-detail-path'
      preLoaderRoute: typeof AuthenticatedDevComponentsOrderDetailPathRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev-components/detail-view-formatter': {
      id: '/_authenticated/dev-components/detail-view-formatter'
      path: '/dev-components/detail-view-formatter'
      fullPath: '/dev-components/detail-view-formatter'
      preLoaderRoute: typeof AuthenticatedDevComponentsDetailViewFormatterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$objectName/$recordId': {
      id: '/_authenticated/$objectName/$recordId'
      path: '/$objectName/$recordId'
      fullPath: '/$objectName/$recordId'
      preLoaderRoute: typeof AuthenticatedObjectNameRecordIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/users/': {
      id: '/_authenticated/settings/users/'
      path: '/'
      fullPath: '/settings/users/'
      preLoaderRoute: typeof AuthenticatedSettingsUsersIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsUsersRoute
    }
    '/_authenticated/settings/translations/': {
      id: '/_authenticated/settings/translations/'
      path: '/'
      fullPath: '/settings/translations/'
      preLoaderRoute: typeof AuthenticatedSettingsTranslationsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsTranslationsRoute
    }
    '/_authenticated/settings/sidebar-assignment/': {
      id: '/_authenticated/settings/sidebar-assignment/'
      path: '/'
      fullPath: '/settings/sidebar-assignment/'
      preLoaderRoute: typeof AuthenticatedSettingsSidebarAssignmentIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsSidebarAssignmentRoute
    }
    '/_authenticated/settings/profiles/': {
      id: '/_authenticated/settings/profiles/'
      path: '/'
      fullPath: '/settings/profiles/'
      preLoaderRoute: typeof AuthenticatedSettingsProfilesIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsProfilesRoute
    }
    '/_authenticated/settings/object-manager/': {
      id: '/_authenticated/settings/object-manager/'
      path: '/'
      fullPath: '/settings/object-manager/'
      preLoaderRoute: typeof AuthenticatedSettingsObjectManagerIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsObjectManagerRoute
    }
    '/_authenticated/settings/email-templates/': {
      id: '/_authenticated/settings/email-templates/'
      path: '/'
      fullPath: '/settings/email-templates/'
      preLoaderRoute: typeof AuthenticatedSettingsEmailTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsEmailTemplatesRoute
    }
    '/_authenticated/settings/users/$userId': {
      id: '/_authenticated/settings/users/$userId'
      path: '/$userId'
      fullPath: '/settings/users/$userId'
      preLoaderRoute: typeof AuthenticatedSettingsUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedSettingsUsersRoute
    }
    '/_authenticated/settings/profiles/$profileName': {
      id: '/_authenticated/settings/profiles/$profileName'
      path: '/$profileName'
      fullPath: '/settings/profiles/$profileName'
      preLoaderRoute: typeof AuthenticatedSettingsProfilesProfileNameRouteImport
      parentRoute: typeof AuthenticatedSettingsProfilesRoute
    }
    '/_authenticated/settings/object-manager/$objectName': {
      id: '/_authenticated/settings/object-manager/$objectName'
      path: '/$objectName'
      fullPath: '/settings/object-manager/$objectName'
      preLoaderRoute: typeof AuthenticatedSettingsObjectManagerObjectNameRouteImport
      parentRoute: typeof AuthenticatedSettingsObjectManagerRoute
    }
    '/_authenticated/settings/email-templates/$templateKey': {
      id: '/_authenticated/settings/email-templates/$templateKey'
      path: '/$templateKey'
      fullPath: '/settings/email-templates/$templateKey'
      preLoaderRoute: typeof AuthenticatedSettingsEmailTemplatesTemplateKeyRouteImport
      parentRoute: typeof AuthenticatedSettingsEmailTemplatesRoute
    }
    '/_authenticated/settings/profiles/$profileName/': {
      id: '/_authenticated/settings/profiles/$profileName/'
      path: '/'
      fullPath: '/settings/profiles/$profileName/'
      preLoaderRoute: typeof AuthenticatedSettingsProfilesProfileNameIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsProfilesProfileNameRoute
    }
    '/_authenticated/settings/profiles/$profileName/objects': {
      id: '/_authenticated/settings/profiles/$profileName/objects'
      path: '/objects'
      fullPath: '/settings/profiles/$profileName/objects'
      preLoaderRoute: typeof AuthenticatedSettingsProfilesProfileNameObjectsRouteImport
      parentRoute: typeof AuthenticatedSettingsProfilesProfileNameRoute
    }
    '/_authenticated/settings/profiles/$profileName/list-views': {
      id: '/_authenticated/settings/profiles/$profileName/list-views'
      path: '/list-views'
      fullPath: '/settings/profiles/$profileName/list-views'
      preLoaderRoute: typeof AuthenticatedSettingsProfilesProfileNameListViewsRouteImport
      parentRoute: typeof AuthenticatedSettingsProfilesProfileNameRoute
    }
    '/_authenticated/settings/profiles/$profileName/global-actions': {
      id: '/_authenticated/settings/profiles/$profileName/global-actions'
      path: '/global-actions'
      fullPath: '/settings/profiles/$profileName/global-actions'
      preLoaderRoute: typeof AuthenticatedSettingsProfilesProfileNameGlobalActionsRouteImport
      parentRoute: typeof AuthenticatedSettingsProfilesProfileNameRoute
    }
    '/_authenticated/settings/profiles/$profileName/objects/': {
      id: '/_authenticated/settings/profiles/$profileName/objects/'
      path: '/'
      fullPath: '/settings/profiles/$profileName/objects/'
      preLoaderRoute: typeof AuthenticatedSettingsProfilesProfileNameObjectsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsProfilesProfileNameObjectsRoute
    }
    '/_authenticated/settings/profiles/$profileName/objects/$objectName': {
      id: '/_authenticated/settings/profiles/$profileName/objects/$objectName'
      path: '/$objectName'
      fullPath: '/settings/profiles/$profileName/objects/$objectName'
      preLoaderRoute: typeof AuthenticatedSettingsProfilesProfileNameObjectsObjectNameRouteImport
      parentRoute: typeof AuthenticatedSettingsProfilesProfileNameObjectsRoute
    }
  }
}

interface AuthenticatedSettingsEmailTemplatesRouteChildren {
  AuthenticatedSettingsEmailTemplatesTemplateKeyRoute: typeof AuthenticatedSettingsEmailTemplatesTemplateKeyRoute
  AuthenticatedSettingsEmailTemplatesIndexRoute: typeof AuthenticatedSettingsEmailTemplatesIndexRoute
}

const AuthenticatedSettingsEmailTemplatesRouteChildren: AuthenticatedSettingsEmailTemplatesRouteChildren =
  {
    AuthenticatedSettingsEmailTemplatesTemplateKeyRoute:
      AuthenticatedSettingsEmailTemplatesTemplateKeyRoute,
    AuthenticatedSettingsEmailTemplatesIndexRoute:
      AuthenticatedSettingsEmailTemplatesIndexRoute,
  }

const AuthenticatedSettingsEmailTemplatesRouteWithChildren =
  AuthenticatedSettingsEmailTemplatesRoute._addFileChildren(
    AuthenticatedSettingsEmailTemplatesRouteChildren,
  )

interface AuthenticatedSettingsObjectManagerRouteChildren {
  AuthenticatedSettingsObjectManagerObjectNameRoute: typeof AuthenticatedSettingsObjectManagerObjectNameRoute
  AuthenticatedSettingsObjectManagerIndexRoute: typeof AuthenticatedSettingsObjectManagerIndexRoute
}

const AuthenticatedSettingsObjectManagerRouteChildren: AuthenticatedSettingsObjectManagerRouteChildren =
  {
    AuthenticatedSettingsObjectManagerObjectNameRoute:
      AuthenticatedSettingsObjectManagerObjectNameRoute,
    AuthenticatedSettingsObjectManagerIndexRoute:
      AuthenticatedSettingsObjectManagerIndexRoute,
  }

const AuthenticatedSettingsObjectManagerRouteWithChildren =
  AuthenticatedSettingsObjectManagerRoute._addFileChildren(
    AuthenticatedSettingsObjectManagerRouteChildren,
  )

interface AuthenticatedSettingsProfilesProfileNameObjectsRouteChildren {
  AuthenticatedSettingsProfilesProfileNameObjectsObjectNameRoute: typeof AuthenticatedSettingsProfilesProfileNameObjectsObjectNameRoute
  AuthenticatedSettingsProfilesProfileNameObjectsIndexRoute: typeof AuthenticatedSettingsProfilesProfileNameObjectsIndexRoute
}

const AuthenticatedSettingsProfilesProfileNameObjectsRouteChildren: AuthenticatedSettingsProfilesProfileNameObjectsRouteChildren =
  {
    AuthenticatedSettingsProfilesProfileNameObjectsObjectNameRoute:
      AuthenticatedSettingsProfilesProfileNameObjectsObjectNameRoute,
    AuthenticatedSettingsProfilesProfileNameObjectsIndexRoute:
      AuthenticatedSettingsProfilesProfileNameObjectsIndexRoute,
  }

const AuthenticatedSettingsProfilesProfileNameObjectsRouteWithChildren =
  AuthenticatedSettingsProfilesProfileNameObjectsRoute._addFileChildren(
    AuthenticatedSettingsProfilesProfileNameObjectsRouteChildren,
  )

interface AuthenticatedSettingsProfilesProfileNameRouteChildren {
  AuthenticatedSettingsProfilesProfileNameGlobalActionsRoute: typeof AuthenticatedSettingsProfilesProfileNameGlobalActionsRoute
  AuthenticatedSettingsProfilesProfileNameListViewsRoute: typeof AuthenticatedSettingsProfilesProfileNameListViewsRoute
  AuthenticatedSettingsProfilesProfileNameObjectsRoute: typeof AuthenticatedSettingsProfilesProfileNameObjectsRouteWithChildren
  AuthenticatedSettingsProfilesProfileNameIndexRoute: typeof AuthenticatedSettingsProfilesProfileNameIndexRoute
}

const AuthenticatedSettingsProfilesProfileNameRouteChildren: AuthenticatedSettingsProfilesProfileNameRouteChildren =
  {
    AuthenticatedSettingsProfilesProfileNameGlobalActionsRoute:
      AuthenticatedSettingsProfilesProfileNameGlobalActionsRoute,
    AuthenticatedSettingsProfilesProfileNameListViewsRoute:
      AuthenticatedSettingsProfilesProfileNameListViewsRoute,
    AuthenticatedSettingsProfilesProfileNameObjectsRoute:
      AuthenticatedSettingsProfilesProfileNameObjectsRouteWithChildren,
    AuthenticatedSettingsProfilesProfileNameIndexRoute:
      AuthenticatedSettingsProfilesProfileNameIndexRoute,
  }

const AuthenticatedSettingsProfilesProfileNameRouteWithChildren =
  AuthenticatedSettingsProfilesProfileNameRoute._addFileChildren(
    AuthenticatedSettingsProfilesProfileNameRouteChildren,
  )

interface AuthenticatedSettingsProfilesRouteChildren {
  AuthenticatedSettingsProfilesProfileNameRoute: typeof AuthenticatedSettingsProfilesProfileNameRouteWithChildren
  AuthenticatedSettingsProfilesIndexRoute: typeof AuthenticatedSettingsProfilesIndexRoute
}

const AuthenticatedSettingsProfilesRouteChildren: AuthenticatedSettingsProfilesRouteChildren =
  {
    AuthenticatedSettingsProfilesProfileNameRoute:
      AuthenticatedSettingsProfilesProfileNameRouteWithChildren,
    AuthenticatedSettingsProfilesIndexRoute:
      AuthenticatedSettingsProfilesIndexRoute,
  }

const AuthenticatedSettingsProfilesRouteWithChildren =
  AuthenticatedSettingsProfilesRoute._addFileChildren(
    AuthenticatedSettingsProfilesRouteChildren,
  )

interface AuthenticatedSettingsSidebarAssignmentRouteChildren {
  AuthenticatedSettingsSidebarAssignmentIndexRoute: typeof AuthenticatedSettingsSidebarAssignmentIndexRoute
}

const AuthenticatedSettingsSidebarAssignmentRouteChildren: AuthenticatedSettingsSidebarAssignmentRouteChildren =
  {
    AuthenticatedSettingsSidebarAssignmentIndexRoute:
      AuthenticatedSettingsSidebarAssignmentIndexRoute,
  }

const AuthenticatedSettingsSidebarAssignmentRouteWithChildren =
  AuthenticatedSettingsSidebarAssignmentRoute._addFileChildren(
    AuthenticatedSettingsSidebarAssignmentRouteChildren,
  )

interface AuthenticatedSettingsTranslationsRouteChildren {
  AuthenticatedSettingsTranslationsIndexRoute: typeof AuthenticatedSettingsTranslationsIndexRoute
}

const AuthenticatedSettingsTranslationsRouteChildren: AuthenticatedSettingsTranslationsRouteChildren =
  {
    AuthenticatedSettingsTranslationsIndexRoute:
      AuthenticatedSettingsTranslationsIndexRoute,
  }

const AuthenticatedSettingsTranslationsRouteWithChildren =
  AuthenticatedSettingsTranslationsRoute._addFileChildren(
    AuthenticatedSettingsTranslationsRouteChildren,
  )

interface AuthenticatedSettingsUsersRouteChildren {
  AuthenticatedSettingsUsersUserIdRoute: typeof AuthenticatedSettingsUsersUserIdRoute
  AuthenticatedSettingsUsersIndexRoute: typeof AuthenticatedSettingsUsersIndexRoute
}

const AuthenticatedSettingsUsersRouteChildren: AuthenticatedSettingsUsersRouteChildren =
  {
    AuthenticatedSettingsUsersUserIdRoute:
      AuthenticatedSettingsUsersUserIdRoute,
    AuthenticatedSettingsUsersIndexRoute: AuthenticatedSettingsUsersIndexRoute,
  }

const AuthenticatedSettingsUsersRouteWithChildren =
  AuthenticatedSettingsUsersRoute._addFileChildren(
    AuthenticatedSettingsUsersRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsEmailRoute: typeof AuthenticatedSettingsEmailRoute
  AuthenticatedSettingsEmailTemplatesRoute: typeof AuthenticatedSettingsEmailTemplatesRouteWithChildren
  AuthenticatedSettingsFilesRoute: typeof AuthenticatedSettingsFilesRoute
  AuthenticatedSettingsNotificationSettingsRoute: typeof AuthenticatedSettingsNotificationSettingsRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsObjectManagerRoute: typeof AuthenticatedSettingsObjectManagerRouteWithChildren
  AuthenticatedSettingsOrganizationRoute: typeof AuthenticatedSettingsOrganizationRoute
  AuthenticatedSettingsProfilesRoute: typeof AuthenticatedSettingsProfilesRouteWithChildren
  AuthenticatedSettingsSidebarAssignmentRoute: typeof AuthenticatedSettingsSidebarAssignmentRouteWithChildren
  AuthenticatedSettingsTenantRoute: typeof AuthenticatedSettingsTenantRoute
  AuthenticatedSettingsTranslationsRoute: typeof AuthenticatedSettingsTranslationsRouteWithChildren
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRouteWithChildren
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsEmailRoute: AuthenticatedSettingsEmailRoute,
    AuthenticatedSettingsEmailTemplatesRoute:
      AuthenticatedSettingsEmailTemplatesRouteWithChildren,
    AuthenticatedSettingsFilesRoute: AuthenticatedSettingsFilesRoute,
    AuthenticatedSettingsNotificationSettingsRoute:
      AuthenticatedSettingsNotificationSettingsRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsObjectManagerRoute:
      AuthenticatedSettingsObjectManagerRouteWithChildren,
    AuthenticatedSettingsOrganizationRoute:
      AuthenticatedSettingsOrganizationRoute,
    AuthenticatedSettingsProfilesRoute:
      AuthenticatedSettingsProfilesRouteWithChildren,
    AuthenticatedSettingsSidebarAssignmentRoute:
      AuthenticatedSettingsSidebarAssignmentRouteWithChildren,
    AuthenticatedSettingsTenantRoute: AuthenticatedSettingsTenantRoute,
    AuthenticatedSettingsTranslationsRoute:
      AuthenticatedSettingsTranslationsRouteWithChildren,
    AuthenticatedSettingsUsersRoute:
      AuthenticatedSettingsUsersRouteWithChildren,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFilesRoute: typeof AuthenticatedFilesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedObjectNameRecordIdRoute: typeof AuthenticatedObjectNameRecordIdRoute
  AuthenticatedDevComponentsDetailViewFormatterRoute: typeof AuthenticatedDevComponentsDetailViewFormatterRoute
  AuthenticatedDevComponentsOrderDetailPathRoute: typeof AuthenticatedDevComponentsOrderDetailPathRoute
  AuthenticatedDevComponentsSalesforcePathRoute: typeof AuthenticatedDevComponentsSalesforcePathRoute
  AuthenticatedObjectNameIndexRoute: typeof AuthenticatedObjectNameIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFilesRoute: AuthenticatedFilesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedObjectNameRecordIdRoute: AuthenticatedObjectNameRecordIdRoute,
  AuthenticatedDevComponentsDetailViewFormatterRoute:
    AuthenticatedDevComponentsDetailViewFormatterRoute,
  AuthenticatedDevComponentsOrderDetailPathRoute:
    AuthenticatedDevComponentsOrderDetailPathRoute,
  AuthenticatedDevComponentsSalesforcePathRoute:
    AuthenticatedDevComponentsSalesforcePathRoute,
  AuthenticatedObjectNameIndexRoute: AuthenticatedObjectNameIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ChangePasswordRequiredRoute: ChangePasswordRequiredRoute,
  ConfirmEmailChangeRoute: ConfirmEmailChangeRoute,
  LoginRoute: LoginRoute,
  LoginVerify2faRoute: LoginVerify2faRoute,
  SecureAccessRoute: SecureAccessRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
